# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: owlr-lambda-demo

provider:
  name: aws
  stage: test
  runtime: nodejs6.10
  region: us-east-1
  role: arn:aws:iam::842366231918:role/lambda_basic_execution

functions:
  generatethumb:
    handler: handler.generatethumb
    name: owlr-lambda-demo-generatethumb
    events:
      - s3:
          bucket: owlr-lambda-demo-a
          event: s3:ObjectCreated:*
          timeout: 10
          rules:
            - prefix: snapshots/
